package failing

// this will be used to test behaviour when a test fails
func sum(a, b int) int {
	return a * b
}
